-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2026-04-25 12:43:32 BDT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



CREATE TABLE advising_windows (
    window_id      NUMBER NOT NULL,
    semester_id    NUMBER NOT NULL,
    target_role    VARCHAR2(10) NOT NULL,
    min_credits    NUMBER(5) DEFAULT 0,
    max_credits    NUMBER(5) DEFAULT 9999,
    min_cgpa       NUMBER(4, 2),
    max_cgpa       NUMBER(4, 2),
    start_time     TIMESTAMP NOT NULL,
    end_time       TIMESTAMP NOT NULL,
    reason_label   VARCHAR2(100)
);

ALTER TABLE advising_windows
    ADD CHECK ( target_role IN (
        'ADMIN',
        'FACULTY',
        'STUDENT'
    ) );

ALTER TABLE advising_windows ADD CONSTRAINT advising_windows_pk PRIMARY KEY ( window_id );

CREATE TABLE course_offerings (
    offering_id       NUMBER NOT NULL,
    semesters_id      NUMBER NOT NULL,
    course_id         NUMBER NOT NULL,
    offering_status   VARCHAR2(15) DEFAULT 'OPEN'
);

ALTER TABLE course_offerings
    ADD CHECK ( offering_status IN (
        'CANCELLED',
        'CLOSED',
        'OPEN'
    ) );

ALTER TABLE course_offerings ADD CONSTRAINT course_offerings_pk PRIMARY KEY ( offering_id );

ALTER TABLE course_offerings ADD CONSTRAINT offerings_course_id_un UNIQUE ( semesters_id,
                                                                            course_id );

CREATE TABLE course_prerequisites (
    courses_course_id    NUMBER NOT NULL,
    courses_course_id1   NUMBER NOT NULL
);

ALTER TABLE course_prerequisites ADD CONSTRAINT chk_no_self_prereq CHECK ( course_id <> prereq_course_id );

ALTER TABLE course_prerequisites ADD CONSTRAINT course_prerequisites_pk PRIMARY KEY ( courses_course_id,
                                                                                      courses_course_id1 );

CREATE TABLE course_sections (
    section_id        NUMBER NOT NULL,
    offering_id       NUMBER NOT NULL,
    section_name      VARCHAR2(10) NOT NULL,
    faculty_id        VARCHAR2(20),
    room_no           VARCHAR2(20),
    class_schedule    VARCHAR2(100),
    max_capacity      NUMBER(4) NOT NULL,
    available_seats   NUMBER(4) NOT NULL,
    section_status    VARCHAR2(15) DEFAULT 'OPEN'
);

ALTER TABLE course_sections
    ADD CHECK ( section_status IN (
        'CLOSED',
        'FULL',
        'OPEN'
    ) );

ALTER TABLE course_sections
    ADD CONSTRAINT chk_section_seats CHECK ( available_seats >= 0
                                             AND available_seats <= max_capacity );

ALTER TABLE course_sections ADD CONSTRAINT course_sections_pk PRIMARY KEY ( section_id );

ALTER TABLE course_sections ADD CONSTRAINT course_sections_name_un UNIQUE ( offering_id,
                                                                            section_name );

CREATE TABLE courses (
    course_id      NUMBER NOT NULL,
    course_code    VARCHAR2(15) NOT NULL,
    course_title   VARCHAR2(100) NOT NULL,
    credits        NUMBER(2) NOT NULL,
    department     VARCHAR2(50),
    level_no       NUMBER(2),
    is_active      CHAR(1) DEFAULT 'Y'
);

ALTER TABLE courses
    ADD CHECK ( is_active IN (
        'N',
        'Y'
    ) );

ALTER TABLE courses ADD CONSTRAINT courses_pk PRIMARY KEY ( course_id );

ALTER TABLE courses ADD CONSTRAINT courses_course_code_un UNIQUE ( course_code );

CREATE TABLE enrollments (
    enrollment_id       NUMBER NOT NULL,
    students_id         VARCHAR2(20) NOT NULL,
    section_id          NUMBER NOT NULL,
    enrolled_at         TIMESTAMP DEFAULT systimestamp,
    users_user_id       VARCHAR2(20) NOT NULL,
    enrollment_source   VARCHAR2(20) NOT NULL,
    enrollment_status   VARCHAR2(15) DEFAULT 'ENROLLED',
    dropped_at          TIMESTAMP,
    users_user_id1      VARCHAR2(20),
    drop_reason         VARCHAR2(200)
);

ALTER TABLE enrollments
    ADD CHECK ( enrollment_source IN (
        'ADMIN',
        'AUTO',
        'FACULTY',
        'SELF'
    ) );

ALTER TABLE enrollments
    ADD CHECK ( enrollment_status IN (
        'DROPPED',
        'ENROLLED'
    ) );

ALTER TABLE enrollments ADD CONSTRAINT enrollments_pk PRIMARY KEY ( enrollment_id );

ALTER TABLE enrollments ADD CONSTRAINT enrollments_section_id_un UNIQUE ( students_id,
                                                                          section_id );

CREATE TABLE faculty (
    user_id        VARCHAR2(20) NOT NULL,
    faculty_name   VARCHAR2(100) NOT NULL,
    email          VARCHAR2(100),
    department     VARCHAR2(50),
    designation    VARCHAR2(50),
    phone          VARCHAR2(20)
);

ALTER TABLE faculty ADD CONSTRAINT faculty_pk PRIMARY KEY ( user_id );

ALTER TABLE faculty ADD CONSTRAINT faculty_email_un UNIQUE ( email );

CREATE TABLE provenance_log (
    log_id             NUMBER NOT NULL,
    source_table       VARCHAR2(50) NOT NULL,
    row_pk             VARCHAR2(100) NOT NULL,
    operation_type     VARCHAR2(20) NOT NULL,
    users_user_id      VARCHAR2(20),
    actor_role         VARCHAR2(20),
    event_time         TIMESTAMP DEFAULT systimestamp,
    why_provenance     VARCHAR2(300),
    where_provenance   VARCHAR2(300),
    how_provenance     VARCHAR2(300),
    old_value          CLOB,
    new_value          CLOB,
    request_id         NUMBER
);

ALTER TABLE provenance_log
    ADD CHECK ( operation_type IN (
        'ADD',
        'APPROVE',
        'AUTO-ADVISE',
        'DELETE',
        'DROP',
        'INSERT',
        'UPDATE'
    ) );

ALTER TABLE provenance_log ADD CONSTRAINT provenance_log_pk PRIMARY KEY ( log_id );

CREATE TABLE registration_requests (
    request_id       NUMBER NOT NULL,
    students_id      VARCHAR2(20) NOT NULL,
    section_id       NUMBER NOT NULL,
    users_id         VARCHAR2(20) NOT NULL,
    request_type     VARCHAR2(20) NOT NULL,
    request_reason   VARCHAR2(200),
    request_time     TIMESTAMP DEFAULT systimestamp,
    request_status   VARCHAR2(15) DEFAULT 'PENDING',
    processed_at     TIMESTAMP,
    processed_note   VARCHAR2(300)
);

ALTER TABLE registration_requests
    ADD CHECK ( request_type IN (
        'ADD',
        'ADMIN-OVERRIDE',
        'AUTO-ADVISE',
        'DROP',
        'FACULTY-ADVISE'
    ) );

ALTER TABLE registration_requests
    ADD CHECK ( request_status IN (
        'APPROVED',
        'FAILED',
        'PENDING',
        'REJECTED'
    ) );

ALTER TABLE registration_requests ADD CONSTRAINT registration_requests_pk PRIMARY KEY ( request_id );

CREATE TABLE section_schedule (
    schedule_id   NUMBER NOT NULL,
    section_id    NUMBER NOT NULL,
    day_of_week   VARCHAR2(10),
    start_time    TIMESTAMP,
    end_time      TIMESTAMP,
    class_type    VARCHAR2(10)
);

ALTER TABLE section_schedule
    ADD CHECK ( class_type IN (
        'LAB',
        'THEORY'
    ) );

ALTER TABLE section_schedule ADD CONSTRAINT section_schedule_pk PRIMARY KEY ( schedule_id );

CREATE TABLE section_seat_history (
    seat_log_id           NUMBER NOT NULL,
    sections_id           NUMBER NOT NULL,
    old_available_seats   NUMBER(4),
    new_available_seats   NUMBER(4),
    changed_at            TIMESTAMP DEFAULT systimestamp,
    users_user_id         VARCHAR2(20),
    change_reason         VARCHAR2(100),
    request_id            NUMBER
);

-- Sequence for auto-increment PK
CREATE SEQUENCE faculty_messages_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Table
CREATE TABLE faculty_messages (
    message_id   NUMBER          NOT NULL,
    faculty_id   VARCHAR2(20)    NOT NULL,
    subject      VARCHAR2(200)   NOT NULL,
    body         CLOB            NOT NULL,
    sent_at      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    status       VARCHAR2(10)    DEFAULT 'UNREAD' NOT NULL,
    admin_note   VARCHAR2(500),
    read_at      TIMESTAMP,

    CONSTRAINT pk_faculty_messages PRIMARY KEY (message_id),
    CONSTRAINT fk_fm_faculty       FOREIGN KEY (faculty_id)
        REFERENCES faculty(user_id),
    CONSTRAINT chk_fm_status       CHECK (status IN ('UNREAD', 'READ'))
);

-- Auto-increment trigger
CREATE OR REPLACE TRIGGER faculty_messages_trg
    BEFORE INSERT ON faculty_messages
    FOR EACH ROW
BEGIN
    IF :NEW.message_id IS NULL THEN
        :NEW.message_id := faculty_messages_seq.NEXTVAL;
    END IF;
END;
/

ALTER TABLE section_seat_history ADD CONSTRAINT section_seat_history_pk PRIMARY KEY ( seat_log_id );

CREATE TABLE semesters (
    semester_id          NUMBER NOT NULL,
    term_name            VARCHAR2(30) NOT NULL,
    start_date           DATE NOT NULL,
    end_date             DATE NOT NULL,
    registration_start   TIMESTAMP,
    registration_end     TIMESTAMP,
    drop_deadline        TIMESTAMP,
    status               VARCHAR2(15) DEFAULT 'PLANNED'
);

ALTER TABLE semesters
    ADD CHECK ( status IN (
        'ACTIVE',
        'CLOSED',
        'PLANNED'
    ) );

ALTER TABLE semesters ADD CONSTRAINT semesters_pk PRIMARY KEY ( semester_id );

CREATE TABLE students (
    users_user_id        VARCHAR2(20) NOT NULL,
    student_name         VARCHAR2(100) NOT NULL,
    email                VARCHAR2(100),
    department           VARCHAR2(50),
    program              VARCHAR2(50),
    semester_no          NUMBER(2),
    cgpa                 NUMBER(4, 2) DEFAULT 0.00,
    credits_completed    NUMBER(5) DEFAULT 0,
    admission_term       VARCHAR2(20),
    faculty_faculty_id   VARCHAR2(20),
    student_status       VARCHAR2(15) DEFAULT 'ACTIVE'
);

ALTER TABLE students
    ADD CHECK ( student_status IN (
        'ACTIVE',
        'GRADUATED',
        'INACTIVE',
        'PROBATION'
    ) );

ALTER TABLE students ADD CONSTRAINT students_pk PRIMARY KEY ( users_user_id );

ALTER TABLE students ADD CONSTRAINT students_email_un UNIQUE ( email );

CREATE TABLE takes (
    user_id     VARCHAR2(20) NOT NULL,
    course_id   NUMBER NOT NULL,
    grade       VARCHAR2(5)
);

ALTER TABLE takes ADD CONSTRAINT takes_pk PRIMARY KEY ( user_id,
                                                        course_id );

CREATE TABLE users (
    user_id          VARCHAR2(20) NOT NULL,
    password_hash    VARCHAR2(255) NOT NULL,
    role             VARCHAR2(10) NOT NULL,
    account_status   VARCHAR2(15) DEFAULT 'PENDING',
    created_at       TIMESTAMP DEFAULT systimestamp,
    users_user_id    VARCHAR2(20),
    approved_at      TIMESTAMP
);

ALTER TABLE users
    ADD CHECK ( role IN (
        'ADMIN',
        'FACULTY',
        'STUDENT'
    ) );

ALTER TABLE users
    ADD CHECK ( account_status IN (
        'APPROVED',
        'BLOCKED',
        'PENDING',
        'REJECTED'
    ) );

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY ( user_id );

ALTER TABLE course_sections
    ADD CONSTRAINT course_offerings_fk FOREIGN KEY ( offering_id )
        REFERENCES course_offerings ( offering_id );

ALTER TABLE section_schedule
    ADD CONSTRAINT course_sections_fk FOREIGN KEY ( section_id )
        REFERENCES course_sections ( section_id );

ALTER TABLE registration_requests
    ADD CONSTRAINT course_sections_fkv1 FOREIGN KEY ( section_id )
        REFERENCES course_sections ( section_id );

ALTER TABLE section_seat_history
    ADD CONSTRAINT course_sections_fkv2 FOREIGN KEY ( sections_id )
        REFERENCES course_sections ( section_id );

ALTER TABLE course_offerings
    ADD CONSTRAINT courses_fk FOREIGN KEY ( course_id )
        REFERENCES courses ( course_id );

ALTER TABLE course_prerequisites
    ADD CONSTRAINT courses_fkv1 FOREIGN KEY ( courses_course_id1 )
        REFERENCES courses ( course_id );

ALTER TABLE course_prerequisites
    ADD CONSTRAINT courses_fkv3 FOREIGN KEY ( courses_course_id )
        REFERENCES courses ( course_id );

ALTER TABLE enrollments
    ADD CONSTRAINT enrollments_students_fk FOREIGN KEY ( students_id )
        REFERENCES students ( users_user_id );

ALTER TABLE enrollments
    ADD CONSTRAINT enrollments_users_fk FOREIGN KEY ( users_user_id )
        REFERENCES users ( user_id );

ALTER TABLE enrollments
    ADD CONSTRAINT enrollments_users_fkv1 FOREIGN KEY ( users_user_id1 )
        REFERENCES users ( user_id );

ALTER TABLE course_sections
    ADD CONSTRAINT faculty_fk FOREIGN KEY ( faculty_id )
        REFERENCES faculty ( user_id );

ALTER TABLE faculty
    ADD CONSTRAINT faculty_users_fk FOREIGN KEY ( user_id )
        REFERENCES users ( user_id );

ALTER TABLE section_seat_history
    ADD CONSTRAINT history_users_fk FOREIGN KEY ( users_user_id )
        REFERENCES users ( user_id );

ALTER TABLE provenance_log
    ADD CONSTRAINT provenance_log_users_fk FOREIGN KEY ( users_user_id )
        REFERENCES users ( user_id );

ALTER TABLE section_seat_history
    ADD CONSTRAINT registration_requests_fk FOREIGN KEY ( request_id )
        REFERENCES registration_requests ( request_id );

ALTER TABLE provenance_log
    ADD CONSTRAINT requests_fk FOREIGN KEY ( request_id )
        REFERENCES registration_requests ( request_id );

ALTER TABLE enrollments
    ADD CONSTRAINT sections_fk FOREIGN KEY ( section_id )
        REFERENCES course_sections ( section_id );

ALTER TABLE advising_windows
    ADD CONSTRAINT semesters_fk FOREIGN KEY ( semester_id )
        REFERENCES semesters ( semester_id );

ALTER TABLE course_offerings
    ADD CONSTRAINT semesters_fkv2 FOREIGN KEY ( semesters_id )
        REFERENCES semesters ( semester_id );

ALTER TABLE students
    ADD CONSTRAINT students_faculty_fk FOREIGN KEY ( faculty_faculty_id )
        REFERENCES faculty ( user_id );

ALTER TABLE registration_requests
    ADD CONSTRAINT students_fk FOREIGN KEY ( students_id )
        REFERENCES students ( users_user_id );

ALTER TABLE students
    ADD CONSTRAINT students_users_fk FOREIGN KEY ( users_user_id )
        REFERENCES users ( user_id );

ALTER TABLE takes
    ADD CONSTRAINT takes_courses_fk FOREIGN KEY ( course_id )
        REFERENCES courses ( course_id );

ALTER TABLE takes
    ADD CONSTRAINT takes_students_fk FOREIGN KEY ( user_id )
        REFERENCES students ( users_user_id );

ALTER TABLE registration_requests
    ADD CONSTRAINT users_fk FOREIGN KEY ( users_id )
        REFERENCES users ( user_id );

ALTER TABLE users
    ADD CONSTRAINT users_users_fk FOREIGN KEY ( users_user_id )
        REFERENCES users ( user_id );

CREATE SEQUENCE advising_windows_window_id_seq START WITH 1 NOCACHE;

CREATE OR REPLACE TRIGGER advising_windows_window_id_trg BEFORE
    INSERT ON advising_windows
    FOR EACH ROW
BEGIN
    :new.window_id := advising_windows_window_id_seq.nextval;
END;
/

CREATE SEQUENCE course_offerings_offering_id START WITH 1 NOCACHE;

CREATE OR REPLACE TRIGGER course_offerings_offering_id BEFORE
    INSERT ON course_offerings
    FOR EACH ROW
BEGIN
    :new.offering_id := course_offerings_offering_id.nextval;
END;
/

CREATE SEQUENCE course_sections_section_id_seq START WITH 1 NOCACHE;

CREATE OR REPLACE TRIGGER course_sections_section_id_trg BEFORE
    INSERT ON course_sections
    FOR EACH ROW
BEGIN
    :new.section_id := course_sections_section_id_seq.nextval;
END;
/

CREATE SEQUENCE courses_course_id_seq START WITH 1 NOCACHE;

CREATE OR REPLACE TRIGGER courses_course_id_trg BEFORE
    INSERT ON courses
    FOR EACH ROW
BEGIN
    :new.course_id := courses_course_id_seq.nextval;
END;
/

CREATE SEQUENCE enrollments_enrollment_id_seq START WITH 1 NOCACHE;

CREATE OR REPLACE TRIGGER enrollments_enrollment_id_trg BEFORE
    INSERT ON enrollments
    FOR EACH ROW
BEGIN
    :new.enrollment_id := enrollments_enrollment_id_seq.nextval;
END;
/

CREATE SEQUENCE provenance_log_log_id_seq START WITH 1 NOCACHE;

CREATE OR REPLACE TRIGGER provenance_log_log_id_trg BEFORE
    INSERT ON provenance_log
    FOR EACH ROW
BEGIN
    :new.log_id := provenance_log_log_id_seq.nextval;
END;
/

CREATE SEQUENCE registration_requests_request_ START WITH 1 NOCACHE;

CREATE OR REPLACE TRIGGER registration_requests_request_ BEFORE
    INSERT ON registration_requests
    FOR EACH ROW
BEGIN
    :new.request_id := registration_requests_request_.nextval;
END;
/

CREATE SEQUENCE section_schedule_schedule_id START WITH 1 NOCACHE;

CREATE OR REPLACE TRIGGER section_schedule_schedule_id BEFORE
    INSERT ON section_schedule
    FOR EACH ROW
BEGIN
    :new.schedule_id := section_schedule_schedule_id.nextval;
END;
/

CREATE SEQUENCE section_seat_history_seat_log_ START WITH 1 NOCACHE;

CREATE OR REPLACE TRIGGER section_seat_history_seat_log_ BEFORE
    INSERT ON section_seat_history
    FOR EACH ROW
BEGIN
    :new.seat_log_id := section_seat_history_seat_log_.nextval;
END;
/

CREATE SEQUENCE semesters_semester_id_seq START WITH 1 NOCACHE;

CREATE OR REPLACE TRIGGER semesters_semester_id_trg BEFORE
    INSERT ON semesters
    FOR EACH ROW
BEGIN
    :new.semester_id := semesters_semester_id_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            15
-- CREATE INDEX                             0
-- ALTER TABLE                             63
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                          10
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                         10
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
